<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('rooms')->insert([
            ["name" => "Istanbul", "roomtypes_id" => 1, "long_desc" => "lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam ut, asperiores", "price" => 69.99, "discount" => 0.10, "king_bed" => 1, "sofa_bed" => 1, "max_guests" => 4, "surface" => 80],
            ["name" => "Tanger", "roomtypes_id" => 2, "long_desc" => "lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam ut, asperiores", "price" => 69.99, "discount" => 0.10, "king_bed" => 1, "sofa_bed" => 1, "max_guests" => 2, "surface" => 80],
            ["name" => "Tokyo", "roomtypes_id" => 3, "long_desc" => "lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam ut, asperiores", "price" => 69.99, "discount" => 0.10, "king_bed" => 1, "sofa_bed" => 1, "max_guests" => 2, "surface" => 80],
            ["name" => "Paris", "roomtypes_id" => 4, "long_desc" => "lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam ut, asperiores", "price" => 108.99, "discount" => 0.10, "king_bed" => 1, "sofa_bed" => 1, "max_guests" => 2, "surface" => 80],
            ["name" => "Rio de Janeiro", "roomtypes_id" => 1, "long_desc" => "lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam ut, asperiores", "price" => 109.99, "discount" => 0.10, "king_bed" => 1, "sofa_bed" => 1, "max_guests" => 2, "surface" => 80],
            ["name" => "Sicilia", "roomtypes_id" => 2, "long_desc" => "lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam ut, asperiores", "price" => 105.99, "discount" => 0.10, "king_bed" => 1, "sofa_bed" => 1, "max_guests" => 2, "surface" => 80],
            ["name" => "Moscou", "roomtypes_id" => 2, "long_desc" => "lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam ut, asperiores", "price" => 94.15, "discount" => 0.01, "king_bed" => 1, "sofa_bed" => 1, "max_guests" => 2, "surface" => 80],
            ["name" => "London", "roomtypes_id" => 2, "long_desc" => "lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam ut, asperiores", "price" => 459.99, "discount" => 0.20, "king_bed" => 2, "sofa_bed" => 1, "max_guests" => 3, "surface" => 100],
            ["name" => "Dubaï", "roomtypes_id" => 4, "long_desc" => "lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam ut, asperiores", "price" => 589.99, "discount" => 0.05, "king_bed" => 2, "sofa_bed" => 1, "max_guests" => 4, "surface" => 150],
        ]);
    }
}
